---
title: "MATH 216 Homework 5"
author: "Delaney Moran"
output: html_document
---


## Admistrative:

Please indicate

* Who you collaborated with: no one
* Roughly how much time you spent on this HW: 3 hrs
* What gave you the most trouble:
* Any comments you have: 


## Question 1:



```{r, echo=FALSE, message=FALSE, warning=FALSE}
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(stringr))
suppressPackageStartupMessages(library(wordcloud))
suppressPackageStartupMessages(library(SnowballC))
suppressPackageStartupMessages(library(tm))
```


Wordclouds: (Non-Shiny)
```{r, echo=FALSE, fig.width=12, fig.height=6}
#import text files
bible <-readLines("bible.txt", encoding="UTF-8") %>%
  as.character()

anneogg <- readLines("Anne.txt", encoding="UTF-8") %>%
  as.character()

biobook <- readLines("biobook.txt", encoding="UTF-8") %>%
  as.character()


#clean it up
more_stopwords<- c("said", "thy", "thee", "ye", "will", "thee", "can", "shall", "hath", "one", "now", "dont", "mrs", "im", "also", "thou", "will", "go", "going", "mr", "shalt", "much", "upon", "us", "even", "get", "say", "unto", "went", "saith", "therefore", "just", "hast", "ive", "didnt", "id", "isnt", "got", "o", "oh")

anneogg_names <- c("marilla", "diana", "matthew", "anne", "lynde")

bible <- bible %>% 
  tolower() %>%
  removeNumbers() %>%
  removePunctuation() %>%
  removeWords(c(stopwords("english"), more_stopwords)) %>%
  stemDocument() %>%
  stripWhitespace()

anneogg <- anneogg %>% 
  tolower() %>%
  removeNumbers() %>%
  removePunctuation() %>%
  removeWords(c(stopwords("english"),more_stopwords, anneogg_names)) %>%
  stemDocument() %>%
  stripWhitespace()

biobook <- biobook %>% 
  tolower() %>%
  removeNumbers() %>%
  removePunctuation() %>%
  removeWords(c(stopwords("english"), more_stopwords)) %>%
  stemDocument() %>%
  stripWhitespace()


#make wordclouds!

anneogg2 <- VectorSource(anneogg) %>% 
  Corpus()
anne_cloud <- wordcloud(anneogg, scale=c(4, 0.5), max.words=25, random.order=FALSE,
          rot.per=0.2, use.r.layout=FALSE, colors=brewer.pal(5, "YlGn"))

bible2 <- VectorSource(bible) %>% 
  Corpus()
bible_cloud <- wordcloud(bible, scale=c(5,0.5), max.words=25, random.order=FALSE,
          rot.per=0.35, use.r.layout=FALSE, colors=brewer.pal(5, "RdPu"))

biobook2 <- VectorSource(biobook) %>% 
  Corpus()
bio_cloud <- wordcloud(biobook, scale=c(5,0.5), max.words=25, random.order=FALSE,
          rot.per=0.35, use.r.layout=FALSE, colors=brewer.pal(5, "BuGn"))



```


